### ISSUE TITLE
Upgrade Laravel Version to V5.

### ISSUE THREAD

**Issue by vrkansagara** [Wildhoney/Magento-on-Angular#107]
Hey I have started to upgrading on my dev branch for the laravel v5 and integration of moa is started.

And having some issue please find my dev repo and help me out.

https://github.com/vrkansagara/Magento-on-Angular/tree/dev  
![screenshot from 2015-10-24 14 04 23](https://cloud.githubusercontent.com/assets/12006483/10709774/3bce5b5e-7a58-11e5-8ceb-79b4c4913a31.png)

**Comment by vrkansagara** [comment]
Ping @Wildhoney   :+1:

**Comment by aonic** [comment]
Hi @vrkansagara is this something you're still working on?

**Comment by vrkansagara** [comment]
@aonic  I am not working on it because I have already opened a PR with migrated code. here https://github.com/Wildhoney/Magento-on-Angular/pull/108
