### ISSUE TITLE
Why not use Magento REST API?

### ISSUE THREAD

**Issue by EliasZ** [Wildhoney/Magento-on-Angular#63]
I might be missing something here, but instead of using Laravel as an API-wrapper for Magento, why not just use the native Magento REST API with [JSON responses](http://www.magentocommerce.com/api/rest/response_formats.html)?
# edit It being limited in functionality might have to do something with it, but how about extending it for your needs?

**Comment by paulchill** [comment]
I am looking to build a Magento App using an Angular Client, is this still maintained?

is there many limitations / restriction on utilising this package to abstract the client away from the magento server and still have all functionality?

What is the procedure with the checkout? how does this send the checkout order to the server?

Many thanks

**Comment by vrkansagara** [comment]
yes community support open for this repository. you can ask for the commercial support if author allows to support you or if any random guys like me also support you on bug fixing and little work if you like so.
thanks the author for this working repository.

**Comment by vrkansagara** [comment]
@paulchill  and make sure to open a new issue if you have so not on closed issue. it make sense to other. thanks,

**Comment by Wildhoney** [comment]
It's definitely still active, but career-wise I'm not involved with Magento any longer, and have moved onto other areas that interest me &ndash; that's why my ability to provide support is somewhat limited, and I apologise for that.

With that said though, I do help whenever I can, but as MoA is now much more community orientated, I feel other people are in a much better position to provide support than I am &ndash; and they are, and **DO** provide lots of support, which is wonderful to see. Happy open-sourcing, folks! :beers:

**Comment by vrkansagara** [comment]
@Wildhoney  am really want to provide more support on this but if possible than can I have some short of commit rights to the repository. if you like so.

I want lot work to do on this repo but community people generally not accept so if possible than allocate me commit rights. thanks.

**Comment by Wildhoney** [comment]
@vrkansagara After a handful of pull requests, I will add you as a contributor to push and pull as you please &mdash; this is the reason @aonic is listed as a contributor :+1:

**Comment by vrkansagara** [comment]
:+1:  thanks @Wildhoney  and @aonic  , I will make help full contribution to this repository. Thaks again.

**Comment by vrkansagara** [comment]
> @vrkansagara After a handful of pull requests, I will add you as a contributor to push and pull as you please — this is the reason @aonic is listed as a contributor 

I got some error. I think you havent set me as contributor or given proper right to the repository.

```
$ git clone git@github.com:Wildhoney/Magento-on-Angular.git
Cloning into 'Magento-on-Angular'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Wildhoney** [comment]
Please open a PR @vrkansagara &ndash; if your first PR looks good, I will add you as a contributor.

**Comment by vrkansagara** [comment]
will open PR soon.

**Comment by vrkansagara** [comment]
have you seen PR #106

**Comment by Wildhoney** [comment]
Yes, although I don't agree that the title of the README necessarily needs changing.

Basically what I'm looking for is that you're a serious contributor to the project, who's going to keep it well maintained, writing good code, and I can only ascertain this once you've had a handful of pull requests merged into the project.

The whole reason for pull requests is that we keep MoA's code well structured, well maintained. If we allowed **everybody** to commit directly to the `master` branch, then the project would soon get out of hand with &mdash; for example &mdash; people committing breaking changes, which then affects everybody else, making it more work for other contributors to reverse those changes.

**Comment by vrkansagara** [comment]
@Wildhoney  As a contributor I am not happy with this PR review process by you and @aonic :-1:

**Comment by aonic** [comment]
Hi @vrkansagara I just added a comment to PR #106 -- the subject of the PR and the actual contents do not line up.

As @Wildhoney mentioned regarding direct access to the `master` branch, most open source projects are contributed to via pull requests. Even I, as a contributor with access, have made all my changes to this projects via pull requests with acceptance and code review from @Wildhoney in the spirit of community collaboration and peer reviews.

**Comment by Wildhoney** [comment]
@aonic Agreed.

Your PR is confusing, and is missing a description of what you're trying to achieve with the vast code changes.
