### ISSUE TITLE
How to implement the checkout process?

### ISSUE THREAD

**Issue by Wildhoney** [Wildhoney/Magento-on-Angular#72]
I'm not too sure on the best way to implement the checkout process. Opening this ticket to hopefully get some good resources together.

I think at the moment the SOAP route is looking the more likely, but I would be interested to see how we could implement this via our Laravel API.

**Comment by fusco** [comment]
Question ? It's possible to create a module's Magento with MOA for use catalog/product nagivation and use a classic magento frontend for others actions (shipping, account, orderers... etc) ?
Thks for answer.
