### ISSUE TITLE
Magento version

### ISSUE THREAD

**Issue by danielkoch** [Wildhoney/Magento-on-Angular#91]
I saw this issue: https://github.com/Wildhoney/Magento-on-Angular/issues/45
What ist the required Magento version. Will MAO work with the current version 1.9.1.0?

**Comment by Wildhoney** [comment]
Although I can't guarantee that it will work with 1.9.1.0 &ndash; I'm *fairly* confident in saying that it *should* work. One of the core philosophies of MoA from the beginning is that it works with a vanilla install of Magento via its bootstrap file. Unless there are vast changes to the Magento infrastucture then all should be good.

Could you please give it a try and report back? You can be our 1.9.1.0 guinea pig :hamster:

**Comment by danielkoch** [comment]
I tried it. I think it works like expected.

**Comment by Wildhoney** [comment]
Good news! :beers:
