### ISSUE TITLE
Magento Product custom field and Laravel API

### ISSUE THREAD

**Issue by creaux** [Wildhoney/Magento-on-Angular#93]
I'm looking for a way to extend Laravel API with custom field from magento. I checked the product object and its _data children that is comming from catalog/product_collection or catalog/product model and custom not contain my custom field. 

Is it necessary to somehow (magento way) extend api or it should be presented simply automatically in api.

**Comment by aonic** [comment]
If you look here https://github.com/Wildhoney/Magento-on-Angular/blob/master/api/app/classes/Moa/API/Provider/Magento/Product.php#L19 you can see its just loading the Magento product object. If the Product object does not contain your attribute then the attribute is not configured properly in Magento admin

**Comment by creaux** [comment]
Many thanks Aonic, yes I found this place as well. I'm just not sure if there is some special configuration needed in Magento. I'm expecting when I add some custom attribute into product in admin area it should be visible in API. On place which you mentioned.

On the other hand in case if my assumption is incorrect there should be some configuration on Magento side. I need to find a way how to do it. There is no proper source with documentation about this case.

**Comment by aonic** [comment]
There is some visibility or "available in search" type value that you need
to set when creating a custom attribute


--
Raja Kapur

**Comment by aonic** [comment]
How did you end up fixing it?


--
Raja Kapur

**Comment by creaux** [comment]
As you mentioned in your previous comment. Each attribute contain visibility option as well as extension of visibility which is defined by visibility per listing or detail view. Cheers
